package com.example.CouponsV3.beans;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company bean class
 * This bean class is used to represent a company that can be added or retrieved from the
 * database.
 */
@Entity
@Table(name="companies")
public class Company {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id; // The id of the company, generated by the database.
	@Column
	private String name; // the name of the company
	@Column
	private String email; // the email of the company
	@Column
	private String password; // the password of the company
	@OneToMany(mappedBy = "companyId", fetch = FetchType.EAGER)
	private List<Coupon> coupons; // the list of coupons of the company
	
	/**
	 * 
	 */
	public Company() {
		super();
	}
	/**
	 * Company CTOR
	 * This constructor will be used to create a new company which later can be saved into a database.
	 * params note: 
	 * id is generated by the database only when a company is inserted.
	 * coupons 
	 * @param name the name of the company
	 * @param email the email of the company
	 * @param password the password of the company
	 */
	public Company(String name, String email, String password) {
		super();
		this.name = name;
		this.email = email;
		this.password = password;
	}
	/**
	 * Company CTOR
	 * This constructor will be used when a company is retrieved from a database
	 * 
	 * @param id the id of the company generated by the database
	 * @param name the name of the company
	 * @param email the email of the company
	 * @param password the password of the company
	 */
	public Company(int id, String name, String email, String password) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.password = password;
	}
	

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * @return the coupons
	 */
	public List<Coupon> getCoupons() {
		return coupons;
	}
	/**
	 * @param coupons the coupons to set
	 */
	public void setCoupons(ArrayList<Coupon> coupons) {
		this.coupons = coupons;
	}

	@Override
	public String toString() {
		return "Company [id=" + id + ", name=" + name + ", email=" + email + ", password=" + password + ", coupons="
				+ coupons + "]";
	}
	
	
	
	
}
