/**
 * 
 */
package com.example.CouponsV3.beans;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Customer bean class
 * This bean class is used to represent a customer that can be added or retrieved from the
 * database.
 *
 */
@Entity
@Table(name="customers")
public class Customer {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id; // The id of the customer, generated by the database.
	@Column
	private String firstName; // The first name of the customer
	@Column
	private String lastName; // The last name of the customer
	@Column
	private String email; // The email of the customer
	@Column
	private String password; // The password of the customer
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(inverseJoinColumns = @JoinColumn(name="coupon_id"),
			          joinColumns = @JoinColumn(name="customer_id"),
			          name="customers_vs_coupons")
	private Set<Coupon> coupons; // The list of coupons of the customer
	
	/**
	 * Hibernate
	 */
	public Customer() {
		super();
	}
	/**
	 * Customer CTOR
	 * This constructor will be used to create a new customer which later can be saved into a database.
	 * params note:
	 * id
	 * coupons
	 * @param firstName The first name of the customer
	 * @param lastName The last name of the customer
	 * @param email The email of the customer
	 * @param password The password of the customer
	 */
	public Customer(String firstName, String lastName, String email, String password) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
	}
	
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	
	/**
	 * @return the first_name
	 */
	public String getFirstName() {
		return firstName;
	}
	/**
	 * @param firstName the first name to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	/**
	 * @return the last name
	 */
	public String getLastName() {
		return lastName;
	}
	/**
	 * @param lastName the last name to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * @return the coupons
	 */
	public Set<Coupon> getCoupons() {
		return coupons;
	}
	/**
	 * @param coupons the coupons to set
	 */
	public void setCoupons(Set<Coupon> coupons) {
		this.coupons = coupons;
	}
	@Override
	public String toString() {
		return "Customer [id=" + id + ", first_name=" + firstName + ", last_name=" + lastName + ", email=" + email
				+ ", password=" + password + ", coupons=" + coupons + "]";
	}
	
	
}
